# Include ~/.local/bin in PATH
export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH

# Term colors
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Less scroll support in Terminator
export LESS=-R

# Debian environment
export DEBFULLNAME="Jordi Bertran de Balanda"
export DEBEMAIL=jordi.bertran@scality.com

# System vars
export ALTERNATE_EDITOR=''
export EDITOR='emacsclient -t'           # $EDITOR should open in terminal
export VISUAL='emacsclient -c -a emacs'   # $VISUAL opens in GUI with non-daemon as alternate

# XDG specification
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# XDG workarounds
export PYLINTHOME="$XDG_CACHE_HOME"/pylint
export IPYTHONDIR="$XDG_CONFIG_HOME"/jupyter
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export PSQLRC="$XDG_CONFIG_HOME"/pg/psqlrc
export PSQL_HISTORY="$XDG_CACHE_HOME"/pg/psql_history
export PGPASSFILE="$XDG_CONFIG_HOME"/pg/pgpass
export PGSERVICEFILE="$XDG_CONFIG_HOME"/pg/pg_service.conf
export VAGRANT_HOME="$XDG_DATA_HOME"/vagrant
export VAGRANT_ALIAS_FILE="$XDG_DATA_HOME"/vagrant/aliases
export LESSKEY="$XDG_CONFIG_HOME"/less/lesskey
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export WORKON_HOME="$XDG_DATA_HOME"/virtualenvs
export SQLITE_HISTORY="$XDG_DATA_HOME"/sqlite_history
export GEM_HOME="$XDG_DATA_HOME"/gem
export GEM_SPEC_CACHE="$XDG_CACHE_HOME"/gem
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc
export SPACEMACSDIR="$XDG_CONFIG_HOME"/spacemacs
alias unit="units --history \"$XDG_CACHE_HOME\"/units_history"
alias yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config"
