# Include ~/.local/bin in PATH
export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH

# Term colors
export TERM="screen-256color"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Less scroll support in Terminator
export LESS=-R

# Debian environment
export DEBFULLNAME="Jordi Bertran de Balanda"
export DEBEMAIL=jordi.bertran@scality.com

# System vars
export ALTERNATE_EDITOR=''
export EDITOR='emacsclient -t'           # $EDITOR should open in terminal
export VISUAL='emacsclient -c -a emacs'   # $VISUAL opens in GUI with non-daemon as alternate
