---

- name: include OS-specific package names
  include_vars:
    file: vars/{{ ansible_os_family | lower }}.yaml
  when: "{{ ansible_os_family | lower }}" in "{{ supported_os }}"

- name: install basic packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ system_packages }}"
  become: true

- name: upgrade pip
  pip:
    name: pip
    state: forcereinstall
    executable: pip3
  become: true

- name: install pip packages
  pip:
    name: "{{ pip_packages }}"
    state: latest
    executable: /usr/local/bin/pip3
    extra_args: --user
  become_user: "{{ username }}"
