- name: install basic packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    "{{ system_packages[ansible_os_family] | default(system_packages['default']) }}"
  become: true

- name: include pip manual install
  import_tasks: pip.yaml

- name: install pip packages
  pip:
    name: "{{ os_packages + pip_packages.common }}"
    state: latest
    executable: /usr/local/bin/pip3
    extra_args: --user
  become: true
  vars:
    os_packages: "{{ pip_packages[ansible_os_family] | default([]) }}"
