- name: copy over $HOME configuration files
  copy:
    src: "files/{{ item }}"
    dest: "{{ homedir }}/{{ item }}"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
  loop: "{{ home_conf_files }}"
  become: true
  tags: ['user_conf']

- name: templated $HOME configuration files
  template:
    src: "templates/{{ item['name'] }}.j2"
    dest: "{{ homedir }}/{{ item['name'] }}"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
  vars:
    template_vars: "{{ item['os_vars'][ansible_os_family] | default(item['os_vars']['default']) }}"
  loop: "{{ template_conf_files }}"
  become: true
  tags: ['templated_conf']

- name: copy over system configuration files
  copy:
    src: "files/{{ item.src }}"
    dest: "{{ item.dst }}"
    mode: "{{ item.mode }}"
  loop: "{{ sys_conf_files }}"
  become: true
  tags: ['system_conf']
