- hosts:
    all
  roles:
    - role: init
      tags: ['user_init']
    - role: packages
      tags: ['packages']
    - role: conf_files
      tags: ['conf_files']
    - role: repos
      tags: ['repos']
